# Schema for the configuration files of the NWC Module module.
ndf_settings.settings:
  type: config_object
  label: 'NDF Module settings'
  mapping:
    facebook_url:
      type: string
      label: 'FacebookUrl'
    twitter_url:
      type: string
      label: 'TwitterUrl'
    youtube_url:
      type: string
      label: 'YoutubeUrl'
    instagram_url:
      type: string
      label: 'InstagramUrl'
    email:
        type: string
        label: 'Email'
    admin_email:
        type: string
        label: 'Administrator Email'
    fax:
      type: string
      label: 'Fax'
    address_en:
      type: text_format
      format: 'full_html'
      value: ''
      label: 'Address'
    address_ar:
      type: text_format
      format: 'full_html'
      value: ''
      label: 'Address'
    copyrights_txt_en:
      type: text_format
      format: 'full_html'
      value: ''
      label: 'Copyrights'
    copyrights_txt_ar:
      type: text_format
      format: 'full_html'
      value: ''
      label: 'Copyrights'
    phone:
        type: string
        label: 'Phone'
    map_location:
      type: string
      label: 'Phone'
