# Schema for the configuration files of the NWC Module module.
ndf_settings.settings:
  type: config_object
  label: 'NWC Module settings'
  mapping:
    facebook_url:
      type: string
      label: 'FacebookUrl'
    twitter_url:
      type: string
      label: 'TwitterUrl'
    youtube_url:
      type: string
      label: 'YoutubeUrl'
    instagram_url:
      type: string
      label: 'InstagramUrl'
    email:
        type: string
        label: 'Email'
    admin_email:
        type: string
        label: 'Administrator Email'
    fax:
      type: string
      label: 'Fax'
    address:
      format: 'full_html'
      label: 'Address'
    phone:
        type: string
        label: 'Phone'
    map_location:
      type: string
      label: 'Phone'
