<?php

/**
 * @file
 * Primary module hooks for NWC Register module.
 */

use \Drupal\Core\Url;

/**
 * Implements hook_form_alter().
 */
function ndf_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if($form_id === 'user_register_form') {
    $form['actions']['submit']['#value'] = t('Create account');
    // Remove inputs descriptions.
    $form['field_first_name']['widget']['#description'] = '';
    $form['field_first_name']['widget'][0]['#description'] = '';
    $form['field_mobile_number']['widget']['#description'] = '';
    $form['field_user_company']['widget'][0]['#description'] = '';
    $form['field_last_name']['widget']['#description'] = '';
    $form['field_last_name']['widget'][0]['#description'] = '';
    $form['account']['mail']['#description'] = '';

    // Altering placeholders.
    $form['field_mobile_number']['widget'][0]['value']['#attributes']["placeholder"] = t('Enter a mobile number');
    $form['field_user_company']['widget'][0]['value']['#attributes']["placeholder"] = t('Enter company name');
    $form['field_first_name']['widget'][0]['value']['#attributes']["placeholder"] = t('Enter first name');
    $form['field_last_name']['widget'][0]['value']['#attributes']["placeholder"] = t('Enter last name');
    $form['account']['mail']["#attributes"]["placeholder"] = t('Enter email address');
  }

  // Alter the login form.
  if ($form_id === 'user_login_form') {
    // Add placeholders.
    $form["name"]["#attributes"]["placeholder"] = t("Enter email address");
    $form["pass"]["#attributes"]["placeholder"] = t("Enter password");

    $url = Url::fromRoute('user.pass')->toString();
    $form['pass']['#suffix'] = '<div class="forget-link"><a href="'.$url.'">'.t('Forgot your password?').'</a></div>';
    // $register_url = Url::fromRoute('user.register')->toString();
    // $form['actions']['submit']['#suffix'] = '<div class="register-link"><span>'.t("Don't have an account?").'</span><a href="'.$register_url.'">'.t('Register now').'</a></div>';
  }

  if(\Drupal::routeMatch()->getRouteName() === 'user.reset') {
    $form['actions']['submit']['#value']  = t('Save');
  }
}

/*
 * Helper function to get config value by key
 */
function get_config($key) {
  if(\Drupal::config('ndf_settings.settings')){
    return \Drupal::config('ndf_settings.settings')->get($key);
  }
  return '';
}
