_core:
  default_config_hash: vKC2q9K1ErwHw_WTZ4RllLPvCwplS7-FQ5gMqVPoiss
langcode: en
entity_label_singular: App
entity_label_plural: Apps
cache_expiration: 900
required_base_fields:
  - callbackUrl
  - displayName
locked_base_fields:
  - displayName
credential_lifetime: 0
