<?php
use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Primary module hooks for ndf_apps module.
 */

 define('APP_DESCRIPTION_LENGTH', 300);
 define('APP_URL_LENGTH', 100);
 define('APP_DISPLAY_NAME_LENGTH', 50);

function ndf_apps_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if($form_id == 'developer_app_edit_for_developer_form' || $form_id == 'developer_app_add_for_developer_form'){
     $form['description']['widget'][0]['value']['#attributes']['maxlength'] = APP_DESCRIPTION_LENGTH;
     $form['callbackUrl']['widget'][0]['value']['#maxlength'] = APP_URL_LENGTH;
     $form['#validate'][] = 'validate_app_form';
  }
}

function check_app_form_inputs_length(&$form, \Drupal\Core\Form\FormStateInterface $form_state){
  $values = $form_state->getValues();
  $description_txt = $values['description'][0]['value'];
}

function validate_app_form(&$form, \Drupal\Core\Form\FormStateInterface $form_state){
  $values = $form_state->getValues();
  $app_name = $values['displayName'][0]['value'];
  if (strlen($description_txt) > APP_DESCRIPTION_LENGTH) {
    $form_state->setErrorByName('description', t('Description exceed max limit'));
  }  
  if (strlen($app_name) > APP_DISPLAY_NAME_LENGTH) {
    $form_state->setErrorByName('displayName', t('App name exceed max limit'));
  }
   if (preg_match("/\p{Zs}/s", $app_name)) {
    $form_state->setErrorByName('displayName', t('App name should not contain spaces'));
  }
}